AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LoginTable:
    Type: "AWS::Serverless::SimpleTable"
  UserLogin:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs8.10
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref LoginTable
      Events:
        Login:
          Type: Api
          Properties:
            Path: /
            Method: post