AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LoginTable:
    Type: "AWS::Serverless::SimpleTable"
  UserLogin:
    # This resource creates a Lambda function.
    Type: "AWS::Serverless::Function"
    Properties:
      # This function uses the Nodejs v8.10 runtime.
      Runtime: nodejs8.10
      # This is the Lambda function's handler.
      Handler: index.handler
      # The location of the Lambda function code.
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref LoginTable
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post